# Generated by Django 6.0.6 on 2026-06-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='user_type',
            field=models.CharField(choices=[('ADM', 'Administrador'), ('CLI', 'Cliente')], default='CLI', max_length=3),
        ),
    ]
