# Generated by Django 6.0.6 on 2026-06-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='code_appointment',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
